#define RVMODEL_ACCESS_FAULT_ADDRESS rvmodel_access_fault_addr
#define RVMODEL_PMP_GRAIN 10
#define RVMODEL_NUM_PMPS 32

#define V_SUPPORTED
#define D_SUPPORTED
#define F_SUPPORTED
#define S_SUPPORTED
#define SSCOFPMF_SUPPORTED
#define SSTC_SUPPORTED
#define SVINVAL_SUPPORTED
#define SVNAPOT_SUPPORTED
#define SVPBMT_SUPPORTED
#define ZFH_SUPPORTED
#define ZFHMIN_SUPPORTED
#define ZBA_SUPPORTED
#define ZBB_SUPPORTED
#define ZBC_SUPPORTED
#define ZBKC_SUPPORTED
#define ZBS_SUPPORTED
#define ZAAMO_SUPPORTED
#define ZALRSC_SUPPORTED
#define ZICBOM_SUPPORTED
#define ZICBOP_SUPPORTED
#define ZICBOZ_SUPPORTED
#define ZICNTR_SUPPORTED
#define ZICOND_SUPPORTED
#define ZICSR_SUPPORTED
#define ZIFENCEI_SUPPORTED
#define ZIHINTPAUSE_SUPPORTED
#define ZIHPM_SUPPORTED
#define ZCA_SUPPORTED
#define ZCD_SUPPORTED
#define ZVFH_SUPPORTED
#define ZVFHMIN_SUPPORTED
#define SV39_SUPPORTED

#define TIME_CSR_IMPLEMENTED 1

// Vector configuration
#define SEWMIN 8
#define ELEN 64
#define MAXINDEXEEW 64

// Supported fractional LMULs for vector
#define LMULf8_SUPPORTED
#define LMULf4_SUPPORTED
#define LMULf2_SUPPORTED
